config/routes.rb
Rails.application.routes.draw do
  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado'
  get 'personas/:id/totales' => 'personas#totales'
  get 'personas/:id/totales_municipio' => 'personas#totales_municipio'

  root 'personas#index'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
   has_one :ayuda
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:nombre)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= simple_form_for(@institution) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<script type="text/javascript">

$(document).ready(function() {

});

</script>

<h1>Listado de Instituciones</h1>

<%= link_to 'New Institution', new_institution_path %>

<table class="table" id="example1">
  <thead>
    <tr>
      <th>#ID</th>
      <th>Nombre</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.id %></td>
        <td><%= institution.nombre %></td>
  <td class="text-right">

        <div class="dropdown open">
            <a href="javascript:;" title="" class="btn medium bg-orange" data-toggle="dropdown">
                <span class="button-content">
                    <i class="glyph-icon font-size-11 icon-cog"></i>
                    <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                </span>
            </a>
            <ul class="dropdown-menu float-right">
        <li>
                <%= link_to  institution  do %>
                 <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>
              </li>
              <li>
                 <%= link_to edit_institution_path(institution) do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>
              </li>
              <li class="divider"></li>
              <li>
                 <%= link_to  institution, method: :delete, data: { confirm: 'Are you sure?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                    <% end -%>
              </li>
            </ul>
        </div>

  </td>


      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>ID</th>
      <th>NOMBRE DE LA INSTITUCION</th>
      <th></th>
    </tr>
  </tfoot>
</table>

<br>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @institution.nombre %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>