config/routes.rb
Rails.application.routes.draw do
  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado'
  get 'personas/:id/totales' => 'personas#totales'
  get 'personas/:id/totales_municipio' => 'personas#totales_municipio'

  root 'personas#index'

end

app/models/ayuda.rb
class Ayuda < ActiveRecord::Base
 belongs_to :institution
	 
end

app/controllers/ayudas_controller.rb
class AyudasController < ApplicationController
  before_action :set_ayuda, only: [:show, :edit, :update, :destroy]

  # GET /ayudas
  # GET /ayudas.json
  def index
    @ayudas = Ayuda.all
  end

  # GET /ayudas/1
  # GET /ayudas/1.json
  def show
  end

  # GET /ayudas/new
  def new
    @ayuda = Ayuda.new
  end

  # GET /ayudas/1/edit
  def edit
  end

  # POST /ayudas
  # POST /ayudas.json
  def create
    @ayuda = Ayuda.new(ayuda_params)

    respond_to do |format|
      if @ayuda.save
        format.html { redirect_to @ayuda, notice: 'Ayuda was successfully created.' }
        format.json { render :show, status: :created, location: @ayuda }
      else
        format.html { render :new }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudas/1
  # PATCH/PUT /ayudas/1.json
  def update
    respond_to do |format|
      if @ayuda.update(ayuda_params)
        format.html { redirect_to @ayuda, notice: 'Ayuda was successfully updated.' }
        format.json { render :show, status: :ok, location: @ayuda }
      else
        format.html { render :edit }
        format.json { render json: @ayuda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudas/1
  # DELETE /ayudas/1.json
  def destroy
    @ayuda.destroy
    respond_to do |format|
      format.html { redirect_to ayudas_url, notice: 'Ayuda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayuda
      @ayuda = Ayuda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayuda_params
      params.require(:ayuda).permit(:nombre, :institution_id)
    end
end

app/helpers/ayudas_helper.rb
module AyudasHelper
end

app/views/ayudas/_form.html.erb
<%= simple_form_for @ayuda, :html=> { class: 'form-horizontal' }  do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>
  <div class="form-inputs">
  	<%= f.association :institution, :label_method => :nombre, :value_method => :id %>

  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/ayudas/edit.html.erb
<h1>Editing Ayuda</h1>

<%= render 'form' %>

<%= link_to 'Show', @ayuda %> |
<%= link_to 'Back', ayudas_path %>

app/views/ayudas/index.html.erb
<p id="notice"><%= notice %></p>

<script type="text/javascript">

$(document).ready(function() {

});

</script>




<h1>Listado de Ayudas</h1>
<%= link_to 'Nueva Ayuda', new_ayuda_path %>
<table class="table" id ="example1" >
  <thead>
    <tr>
      <th>id</th>
      <th>Nombre</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ayudas.each do |ayuda| %>
      <tr>
	<td><%= ayuda.id %></td>
        <td><%= ayuda.nombre %></td>
	<td class="text-right">

        <div class="dropdown open">
            <a href="javascript:;" title="" class="btn medium bg-orange" data-toggle="dropdown">
                <span class="button-content">
                    <i class="glyph-icon font-size-11 icon-cog"></i>
                    <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                </span>
            </a>
            <ul class="dropdown-menu float-right">
			  <li>
                <%= link_to  ayuda  do %>
                 <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>
              </li>
              <li>
                 <%= link_to edit_ayuda_path(ayuda) do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>
              </li>
              <li class="divider"></li>
              <li>
                 <%= link_to  ayuda, method: :delete, data: { confirm: 'Are you sure?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                    <% end -%>
              </li>
            </ul>
        </div>

	</td>


      </tr>
    <% end %>
  </tbody>
	<tfoot>
		<tr>
			<th>ID</th>
			<th>Ayuda</th>
			<th></th>
		</tr>
	</tfoot>

</table>

<br>

<%= link_to 'New Ayuda', new_ayuda_path %>

app/views/ayudas/new.html.erb
<h1>New Ayuda</h1>

<%= render 'form' %>

<%= link_to 'Back', ayudas_path %>

app/views/ayudas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ayuda.nombre %>
</p>

<%= link_to 'Edit', edit_ayuda_path(@ayuda) %> |
<%= link_to 'Back', ayudas_path %>