config/routes.rb
Rails.application.routes.draw do
  resources :localities

  resources :institutions

  resources :ayudas

  resources :personas
  get 'personas/:id/listado' => 'personas#listado'
  get 'personas/:id/totales' => 'personas#totales'
  get 'personas/:id/totales_municipio' => 'personas#totales_municipio'

  root 'personas#index'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :economy, dependent: :destroy
	has_many :conclusions, dependent: :destroy
	has_many :families, dependent: :destroy
	accepts_nested_attributes_for :economy
    accepts_nested_attributes_for :conclusions, reject_if: :all_blank ,	 :allow_destroy => true
    accepts_nested_attributes_for :families , reject_if: :all_blank , :allow_destroy => true
	validates :cedula , uniqueness: true

	
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
   layout "limpio", only: [:listado,:totales,:totales_municipio]
   layout "limpio", only: [:listado,:totales ]
  # GET /personas
  # GET /personas.json

  def listado
   
    @resultado = Persona.all.order(:municipio)
  end

  def reporte_diario
  	
  	
  end



#"SELECT  `personas` . * FROM  `personas` INNER JOIN  `conclusions` ON  `conclusions`.`persona_id` =  `personas`.`id` WHERE (conclusions.fecha BETWEEN  '2015-07-21' AND  '2015-07-31' ) GROUP BY personas.municipio, personas.parroquia, conclusions.solicitud"



def totales_municipio
@fecha_inicio = params[:fecha_inicio]
@fecha_fin = params[:fecha_fin]
@total_municipio= Persona.joins(:conclusions).group("personas.municipio, personas.parroquia, conclusions.solicitud").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-27','2015-07-31').count


#@garcia_total_uniforme = Persona.joins(:conclusions).where("personas.municipio= 'Garcia' and conclusions.solicitud ='Uniformes'").count
#@garcia_total_kitdeportivo = Persona.joins(:conclusions).where("personas.municipio= 'Garcia' and conclusions.solicitud ='Kit deportivo'").count
#@garcia_total_pasaje = Persona.joins(:conclusions).where("personas.municipio= 'Garcia' and conclusions.solicitud ='Pasaje(s)'").count


end





  def totales
  

  @beca_educacion = Conclusion.where(:solicitud=> "Beca Educacion").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @beca_universitaria = Conclusion.where(:solicitud=> "Beca Universitaria").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @econ_Discapacidad= Conclusion.where(:solicitud=> "Econ. Discapacidad").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @operacion= Conclusion.where(:solicitud=> "Operacion").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @estudio_especializado= Conclusion.where(:solicitud=> "Estudio Especializado").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @medicinas= Conclusion.where(:solicitud=> "Medicinas").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @silla_de_ruedas=Conclusion.where(:solicitud=> "Silla de Ruedas").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @andadera=Conclusion.where(:solicitud=> "Andadera").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @baston=Conclusion.where(:solicitud=> "Baston").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @botas_ortopedicas=Conclusion.where(:solicitud=> "Botas Ortopedicas").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @protesis=Conclusion.where(:solicitud=> "Protesis").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @cama=Conclusion.where(:solicitud=> "Cama").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @cama_clinica=Conclusion.where(:solicitud=> "Cama Clinica").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @colchon=Conclusion.where(:solicitud=> "Colchon").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @colchon_clinico=Conclusion.where(:solicitud=> "Colchon Clinico").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @colchon_antiescaras=Conclusion.where(:solicitud=> "Colchon Antiescaras").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @lavadora=Conclusion.where(:solicitud=> "Lavadora").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @cocina=Conclusion.where(:solicitud=> "Cocina ").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @nevera=Conclusion.where(:solicitud=> "Nevera ").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @freezer=Conclusion.where(:solicitud=> "Freezer").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @hijos_de_vzla=Conclusion.where(:solicitud=> "Hijos de Vzla  ").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @amor_mayor=Conclusion.where(:solicitud=> "Amor Mayor").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @vivienda=Conclusion.where(:solicitud=> "Vivienda").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @kit_construccion=Conclusion.where(:solicitud=> "Kit de material de construccion").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @techo=Conclusion.where(:solicitud=> "Techo").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @tanque=Conclusion.where(:solicitud=> "Tanque").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @maquina_coser=Conclusion.where(:solicitud=> "Maquina de Coser").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @uniformes=Conclusion.where(:solicitud=> "Uniformes").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @kit_deportivo=Conclusion.where(:solicitud=> "Kit deportivo").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count
  @pasajes=Conclusion.where(:solicitud=> "Pasaje(s)").where("conclusions.fecha BETWEEN ? AND ? ", '2015-07-20','2015-07-25').count

@totales = @beca_educacion+@beca_universitaria+@econ_Discapacidad+@operacion+@estudio_especializado+@medicinas+@silla_de_ruedas+@andadera+@baston+@botas_ortopedicas+@protesis+@cama+@cama_clinica+@colchon+@colchon_clinico+@colchon_antiescaras+@lavadora+@cocina+@nevera+@freezer+@hijos_de_vzla+@amor_mayor+@vivienda+@kit_construccion+@techo+@tanque+@maquina_coser+@uniformes+@kit_deportivo+@pasajes

  end

  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
    @persona.build_economy
    @persona.families.build  if @persona.families.empty?
    @persona.conclusions.build  if @persona.conclusions.empty?

  end

  # GET /personas/1/edit
  def edit
   # @persona.conclusions.build  
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre1, :nombre2, :apellido1, :apellido2, :cedula, :direccion, :referencia, :municipio, :parroquia, :telefono1, :telefono2,  economy_attributes: [:sector,:empresa,:ingreso_familiar,:tipo_casa,:condiciones_de_vivienda,:persona_hab,:cant_hijos,:enceres_compartidos,:adultos_mayores,:discapacitados,:enfermos,:pobreza_extrema, :descripcion],conclusions_attributes: [:id, :solicitud,:estado,:fecha,:_destroy],families_attributes: [:id, :nombre,:apellido,:parentesco,:_destroy])

    end
end
#:economy[:sector,:empresa,:ingreso_familiar,:tipo_casa,:condiciones_de,:persona_hab,:cant_hijos,:enceres_compartidos,:adultos_mayores,:discapacitados,:enfermos]

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/edit.html.erb
                <div id="page-title">

<h3>
    Editar Persona
    <small>
         se editan los datos de las personas y solicitudes
    </small>
</h3>
                    <div id="breadcrumb-right">
                        <div id="sidebar-search">
                            <input type="text" placeholder="Search..." class="autocomplete-input input tooltip-button" data-placement="bottom" title="Type &apos;jav&apos; to see the available tags..." id="" name="" />
                            <i class="glyph-icon icon-search"></i>
                        </div>
                        <div class="float-right">
                            <a href="javascript:;" class="btn medium bg-white tooltip-button black-modal-60 mrg5R" data-placement="bottom" title="Open modal window">
                                <span class="button-content">
                                    <i class="glyph-icon icon-question"></i>
                                </span>
                            </a>

                            <div class="dropdown">
                                <a href="javascript:;" class="btn medium bg-white" title="Example dropdown" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon icon-cog float-left"></i>
                                        <i class="glyph-icon icon-caret-down float-right"></i>
                                    </span>
                                </a>
                                <div class="dropdown-menu pad0A float-right">
                                    <div class="medium-box">
                                        <div class="bg-gray text-transform-upr font-size-12 font-bold font-gray-dark pad10A">Form example</div>
                                        <div class="pad10A">
                                            <p class="font-gray-dark pad0B">This <span class="label bg-blue-alt">dropdown box</span> uses the Twitter Bootstrap dropdown plugin.</p>
                                            <div class="divider mrg10T mrg10B"></div>

                                                <form id="demo-form" action="" class="col-md-12" method="" />
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Name:
                                                                <span class="required">*</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="email" name="email" data-type="email" data-trigger="change" data-required="true" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Email:
                                                                <span class="required">*</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="email" name="email" data-type="email" data-trigger="change" data-required="true" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Website:
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="website" name="website" data-trigger="change" data-type="url" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="" class="label-description">
                                                                Message:
                                                                <span>20 chars min, 200 max</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <textarea id="message" name="message" data-trigger="keyup" data-rangelength="[20,200]" class="parsley-validated"></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="divider"></div>
                                                    <div class="form-row">
                                                        <input type="hidden" name="superhidden" id="superhidden" />
                                                        <div class="form-input col-md-8 col-md-offset-4">
                                                            <a href="javascript:;" class="btn medium primary-bg radius-all-4" id="demo-form-valid" onclick="javascript:$(&apos;#demo-form&apos;).parsley( &apos;validate&apos; );" title="Validate!">
                                                                <span class="button-content">
                                                                    Validate the form above
                                                                </span>
                                                            </a>
                                                        </div>
                                                    </div>

                                                </form>

                                        </div>

                                        <div class="bg-black font-size-12 font-orange pad10A mrg5L mrg5R">Custom header example</div>
                                        <div class="pad15A">
                                            <p class="font-green text-center font-size-14 pad0B">Fides Admin comes with powerful helpers that you can use to create virtually any style you want. Read the documentation about helper classes to find out more!</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
</div><!-- #page-title -->
<%= render 'form' %>

<%= link_to 'Mostrar', @persona %> |
<%= link_to 'Volver', personas_path %>

app/views/personas/index.html.erb
                <div id="page-title">

<h3>
    Listado de Personas
    <small>
         Listado de solicitantes
    </small>
</h3>
                    <div id="breadcrumb-right">
                        <div id="sidebar-search">
                            <input type="text" placeholder="Search..." class="autocomplete-input input tooltip-button" data-placement="bottom" title="Type &apos;jav&apos; to see the available tags..." id="" name="" />
                            <i class="glyph-icon icon-search"></i>
                        </div>
                        <div class="float-right">
                            <a href="javascript:;" class="btn medium bg-white tooltip-button black-modal-60 mrg5R" data-placement="bottom" title="Open modal window">
                                <span class="button-content">
                                    <i class="glyph-icon icon-question"></i>
                                </span>
                            </a>

                            <div class="dropdown">
                                <a href="javascript:;" class="btn medium bg-white" title="Example dropdown" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon icon-cog float-left"></i>
                                        <i class="glyph-icon icon-caret-down float-right"></i>
                                    </span>
                                </a>
                                <div class="dropdown-menu pad0A float-right">
                                    <div class="medium-box">
                                        <div class="bg-gray text-transform-upr font-size-12 font-bold font-gray-dark pad10A">Form example</div>
                                        <div class="pad10A">
                                            <p class="font-gray-dark pad0B">This <span class="label bg-blue-alt">dropdown box</span> uses the Twitter Bootstrap dropdown plugin.</p>
                                            <div class="divider mrg10T mrg10B"></div>

                                                <form id="demo-form" action="" class="col-md-12" method="" />
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Name:
                                                                <span class="required">*</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="email" name="email" data-type="email" data-trigger="change" data-required="true" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Email:
                                                                <span class="required">*</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="email" name="email" data-type="email" data-trigger="change" data-required="true" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="">
                                                                Website:
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <input type="text" id="website" name="website" data-trigger="change" data-type="url" class="parsley-validated" />
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-label col-md-4">
                                                            <label for="" class="label-description">
                                                                Message:
                                                                <span>20 chars min, 200 max</span>
                                                            </label>
                                                        </div>
                                                        <div class="form-input col-md-8">
                                                            <textarea id="message" name="message" data-trigger="keyup" data-rangelength="[20,200]" class="parsley-validated"></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="divider"></div>
                                                    <div class="form-row">
                                                        <input type="hidden" name="superhidden" id="superhidden" />
                                                        <div class="form-input col-md-8 col-md-offset-4">
                                                            <a href="javascript:;" class="btn medium primary-bg radius-all-4" id="demo-form-valid" onclick="javascript:$(&apos;#demo-form&apos;).parsley( &apos;validate&apos; );" title="Validate!">
                                                                <span class="button-content">
                                                                    Validate the form above
                                                                </span>
                                                            </a>
                                                        </div>
                                                    </div>

                                                </form>

                                        </div>

                                        <div class="bg-black font-size-12 font-orange pad10A mrg5L mrg5R">Custom header example</div>
                                        <div class="pad15A">
                                            <p class="font-green text-center font-size-14 pad0B">Fides Admin comes with powerful helpers that you can use to create virtually any style you want. Read the documentation about helper classes to find out more!</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
</div><!-- #page-title -->


<p id="notice"><%= notice %></p>


<%= link_to 'Nueva Persona', new_persona_path %>

<div class="divider"></div>

<h3>
    Listado de Solicitantes
</h3>
<p class="font-gray-dark">
 Listado de personas solicitando ayudas en la jornada  <b>Corazon Adentro</b> 

</p>



<script type="text/javascript">

$(document).ready(function() {

});

</script>


<table class="table" id="example1">
	<thead>
		<tr>
			<th>#</th>
			<th>Nombres y Apellidos</th>
			<th>Cedula</th>
			<th>Municipio</th>
			<th>Parroquia</th>
			<th>Telefono</th>
			<th></th>

		</tr>
	</thead>
	<tbody>
 <% @personas.each do |persona| %>
      <tr>
      	<td><%= persona.id%></td>
        <td><%= persona.nombre1.capitalize+' '+persona.nombre2.capitalize+' '+persona.apellido1.capitalize+' '+persona.apellido2.capitalize%></td>
        <td><%= persona.cedula %></td>
        <td><%= persona.municipio.capitalize %></td>
        <td><%= persona.parroquia.capitalize %></td>
        <td><%= persona.telefono1 %></td>
        <td class="text-right">
        <div class="dropdown open">
            <a href="javascript:;" title="" class="btn medium bg-orange" data-toggle="dropdown">
                <span class="button-content">
                    <i class="glyph-icon font-size-11 icon-cog"></i>
                    <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                </span>
            </a>
            <ul class="dropdown-menu float-right">
			  <li>
                <%= link_to persona do %>
                 <i class="glyph-icon icon-download mrg5R"></i> Mostrar
                <% end -%>
              </li>
              <li>
                 <%= link_to edit_persona_path(persona) do%>
                   <i class="glyph-icon icon-edit mrg5R"></i> Editar
                 <% end -%>
              </li>
              <li class="divider"></li>
              <li>
                 <%= link_to  persona, method: :delete, data: { confirm: 'Are you sure?' } do%>
                    <i class="glyph-icon icon-remove mrg5R"></i>Borrar
                    <% end -%>
              </li>
            </ul>
        </div>

</td>


      </tr>
    <% end %>


		
	</tbody>
	<tfoot>
		<tr>
			<th>Nombres y Apellidos</th>
			<th>Cedula</th>
			<th>Municipio</th>
			<th>Parroquia</th>
			<th>Telefono</th>
			<th></th>
		</tr>
	</tfoot>
</table>

app/views/personas/reporte_diario.html.erb
<%= simple_form_for @search do |f| %>

  <p>
    <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </p>
  <p>
    fecha<br />
    <%= f.text_field :minimum_price, :size => 7 %> -
    <%= f.text_field :maximum_price, :size => 7 %>
  </p>
  <p<>face/p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/personas/show.html.erb
<br/>
<%= notice %>
<h4 class="heading-1 clearfix">
    <i class="glyph-icon icon-tags heading-icon"></i>
    <div class="heading-content">
       <%=  @persona.nombre1.capitalize+' '+@persona.nombre2.capitalize+' '+@persona.apellido1.capitalize+' '+@persona.apellido2.capitalize%>.
        <small>
        <strong>Cedula de Identidad:</strong> <%= @persona.cedula %><br />
        <strong>Direccion: </strong><%= @persona.direccion.capitalize %>,  <%= @persona.referencia.capitalize %>;  Parroquia <%= @persona.parroquia.capitalize %>, Municipio <%= @persona.municipio.capitalize %>.<br />
        <strong>Telefonos :</strong><%= @persona.telefono1 %>   <%= @persona.telefono2 %>



        </small>
    </div>
</h4>


<div class="divider"></div>
<h4 class="heading-1 clearfix">
Familiares
<small>
<% if !@persona.families.blank?%>
      <% for item in @persona.families %>
        <li>    <%= "<strong> - </strong>#{item.nombre.capitalize} #{item.apellido.capitalize}, #{item.parentesco}".html_safe if !item.nombre.blank? %></li>

    <% end %>
<% end -%>
</small>

<div class="divider"></div>
<h4 class="heading-1 clearfix">
Estudio Socioeconomico
<small><%= "<strong>Empresa donde trabaja ó Ocupacion: #{@persona.economy.empresa}</strong>".html_safe if !@persona.economy.empresa.blank?  %> 
<%="(#{@persona.economy.sector} )" if !@persona.economy.sector.blank? %>
<%="<strong>Ingreso Familiar: </strong> #{@persona.economy.ingreso_familiar}Bs".html_safe if  !@persona.economy.ingreso_familiar.blank? %><br />

<%= "<strong>Tipo de Vivienda: </strong> #{@persona.economy.tipo_casa}".html_safe  if !@persona.economy.tipo_casa.blank?%>
<%= "<strong>Condiciones:  </strong>#{@persona.economy.condiciones_de_vivienda}".html_safe  if !@persona.economy.condiciones_de_vivienda.blank? %>
<%= "<strong>Personas/Hab: </strong> #{ @persona.economy.persona_hab}".html_safe if !@persona.economy.persona_hab.blank?%><br />


<%= "<strong>Cantidade de Hijos: </strong> #{@persona.economy.cant_hijos}".html_safe if !@persona.economy.cant_hijos.blank? %>
<%= "<strong>Enceres Compartidos: </strong>#{@persona.economy.enceres_compartidos}".html_safe if !@persona.economy.enceres_compartidos.blank? %>
<%= "<strong>Adultos Mayores: </strong> #{@persona.economy.adultos_mayores}".html_safe if !@persona.economy.adultos_mayores.blank? %>
<br />
<%= "<strong>Personas Discapacitadas: </strong>#{@persona.economy.discapacitados}".html_safe if !@persona.economy.discapacitados.blank? %>
<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.enfermos}".html_safe if !@persona.economy.enfermos.blank? %>


</small>
</h4>


<div class="divider"></div>
<h4 class="heading-1 clearfix">
Descripcion de la visita

<small>

<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.descripcion}".html_safe if !@persona.economy.descripcion.blank? %>
<%= "<strong>Personas Enfermas : </strong>#{@persona.economy.pobreza_extrema}".html_safe if !@persona.economy.pobreza_extrema.blank? %>

</small>
</h4>

<div class="divider"></div>

<h4 class="heading-1 clearfix">
Conclusión(es)
<small>
<% if !@persona.conclusions.blank? %>
  <% for item in @persona.conclusions %>
  <li>    <%= "<strong>Solicitud : </strong>#{item.solicitud}".html_safe if !item.solicitud.blank? %>
          <%= "<strong>Estado de la solicitud : </strong>#{item.estado}".html_safe if !item.estado.blank? %>
          <%= "<strong>Fecha de la solicitud : </strong>#{item.fecha}".html_safe if !item.fecha.blank? %>
  </li>
  <div class="divider"></div>

  <% end %>
  
<% end %>



</small>
</h4>

<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Volver', personas_path %>